apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-minimal
  labels:
    app: python-minimal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-minimal
  template:
    metadata:
      labels:
        app: python-minimal
    spec:
      containers:
      - name: python-minimal
        image: inseefrlab/onyxia-python-minimal:latest-gpu
        command: ["sleep", "10000"]
        imagePullPolicy: Always
        resources:
          limits:
            nvidia.com/gpu: 1
