name: Main manual workflow with artefacts

on:
  workflow_dispatch:

jobs:
  # init-variables:
  #   uses: ./.github/workflows/init-variables.yml
    # with:
    #    base_image: ubuntu:20.04
    #    base_image_gpu: nvidia/cuda:11.3.1-base-ubuntu20.04
    #    python_version: "3.10.4,3.9.13"
    #    r_version: "4.2.0,4.3.0"
    #    spark_version: "3.2.1,3.3.0"
  base:
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    uses: ./.github/workflows/main-workflow-template-artifact.yml
    with:
      image: base
      context: base
      test: true
      push: false
      base_image: ubuntu:20.04
      base_image_gpu: nvidia/cuda:11.3.1-base-ubuntu20.04
      debug: true
  python-minimal:
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    needs: [base]
    uses: ./.github/workflows/main-workflow-template-artifact.yml
    with:
      image: python-minimal
      context: python-minimal
      test: false
      push: false
      base_image: base
      #base_image_gpu: base-gpu
      python_version_1: 3.9.13
      python_version_2: 3.10.4
  python-datascience:
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    needs: [python-minimal]
    uses: ./.github/workflows/main-workflow-template-artifact.yml
    with:
      image: python-datascience
      context: python-datascience
      test: false
      push: false
      base_image: python-minimal
      #base_image_gpu: base-gpu
      python_version_1: 3.9.13
      python_version_2: 3.10.4
  r-minimal:
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    needs: [base]
    uses: ./.github/workflows/main-workflow-template-artifact.yml
    with:
      image: r-minimal
      context: r-minimal
      test: false
      push: false
      base_image: base
      #base_image_gpu: base-gpu
      r_version_1: 4.1.2
      r_version_2: 4.2.3
  r-datascience:
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    needs: [r-minimal]
    uses: ./.github/workflows/main-workflow-template-artifact.yml
    with:
      image: r-datascience
      context: r-datascience
      test: false
      push: false
      base_image: r-minimal
      #base_image_gpu: base-gpu
      r_version_1: 4.1.2
      r_version_2: 4.2.3
  jupyter:
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    needs: [python-datascience]
    uses: ./.github/workflows/main-workflow-template-artifact.yml
    with:
      image: jupyter-python
      context: jupyter
      test: false
      push: false
      base_image: python-datascience
      python_version_1: 3.9.13
      python_version_2: 3.10.4
  vscode:
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    needs: [python-datascience]
    uses: ./.github/workflows/main-workflow-template-artifact.yml
    with:
      image: vscode-python
      context: vscode
      test: false
      push: false
      base_image: python-datascience
      python_version_1: 3.9.13
      python_version_2: 3.10.4
  pyspark:
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    needs: [python-minimal]
    uses: ./.github/workflows/main-workflow-template-artifact.yml
    with:
      image: pyspark
      context: spark
      test: false
      push: false
      base_image: python-minimal
      python_version_1: 3.9.13
      python_version_2: 3.10.4
      spark_version_1: 3.2.0
      spark_version_2: 3.3.0
  jupyter-pyspark:
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    needs: [pyspark]
    uses: ./.github/workflows/main-workflow-template-artifact.yml
    with:
      image: jupyter-pyspark
      context: jupyter
      test: false
      push: false
      base_image: pyspark
      python_version_1: 3.9.13
      python_version_2: 3.10.4
      spark_version_1: 3.2.0
      spark_version_2: 3.3.0
  r-studio:
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    needs: [r-datascience]
    uses: ./.github/workflows/main-workflow-template-artifact.yml
    with:
      image: rstudio
      context: rstudio
      test: false
      push: false
      base_image: r-datascience
      r_version_1: 4.1.2
      r_version_2: 4.2.3
  sparkr:
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    needs: [r-minimal]
    uses: ./.github/workflows/main-workflow-template-artifact.yml
    with:
      image: sparkr
      context: spark
      test: false
      push: false
      base_image: r-minimal
      r_version_1: 4.1.2
      r_version_2: 4.2.3
      spark_version_1: 3.2.0
      spark_version_2: 3.3.0
  rstudio-sparkr:
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    needs: [sparkr]
    uses: ./.github/workflows/main-workflow-template-artifact.yml
    with:
      image: rstudio-sparkr
      context: rstudio
      test: false
      push: false
      base_image: sparkr
      r_version_1: 4.1.2
      r_version_2: 4.2.3
      spark_version_1: 3.2.0
      spark_version_2: 3.3.0