name: Build and push Docker images

on:
  workflow_dispatch:
  pull_request:
    branches:
    - main

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      base: ${{ steps.filter.outputs.base }}
      jupyter: ${{ steps.filter.outputs.jupyter }}
      python-datascience: ${{ steps.filter.outputs.python-datascience }}
      python-minimal: ${{ steps.filter.outputs.python-minimal }}
      python-pytorch: ${{ steps.filter.outputs.python-pytorch }}
      python-tensorflow: ${{ steps.filter.outputs.python-tensorflow }}
      r-datascience: ${{ steps.filter.outputs.r-datascience }}
      r-minimal: ${{ steps.filter.outputs.r-minimal }}
      r-python-julia: ${{ steps.filter.outputs.r-python-julia }}
      rstudio: ${{ steps.filter.outputs.rstudio }}
      spark: ${{ steps.filter.outputs.spark }}
      vscode: ${{ steps.filter.outputs.vscode }}
    steps:
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          base:
            - 'base/**'
          jupyter:
            - 'jupyter/**'
          python-datascience:
            - 'python-datascience/**'
          python-minimal:
            - 'python-minimal/**'
          python-pytorch:
            - 'python-pytorch/**'
          python-tensorflow:
            - 'python-tensorflow/**'
          r-datascience:
            - 'r-datascience/**'
          r-minimal:
            - 'r-minimal/**'
          r-python-julia:
            - 'r-python-julia/**'
          rstudio:
            - 'rstudio/**'
          spark:
            - 'spark/**'
          vscode:
            - 'vscode/**'
  base:
    needs: changes
    if: ${{ needs.changes.outputs.base == 'true' }}
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: base
      context: base
      test: true
      base_image: ubuntu:20.04
      base_image_gpu: nvidia/cuda:11.7.1-cudnn8-devel-ubuntu20.04
      external_base_image: true
      branch: ${{ github.ref }}
  python-minimal:
    needs: changes
    if: ${{ needs.changes.outputs.python-minimal == 'true' }}
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: python-minimal
      context: python-minimal
      test: true
      base_image: base
      python_version_1: 3.9.13
      python_version_2: 3.10.4
      branch: ${{ github.ref }}
  python-datascience:
    needs: changes
    if: ${{ needs.changes.outputs.python-datascience == 'true' }}
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: python-datascience
      context: python-datascience
      test: true
      base_image: python-minimal
      python_version_1: 3.9.13
      python_version_2: 3.10.4
      branch: ${{ github.ref }}
  python-pytorch:
    needs: changes
    if: ${{ needs.changes.outputs.python-pytorch == 'true' }}
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: python-pytorch
      context: python-pytorch
      test: true
      base_image: python-minimal
      python_version_1: 3.9.13
      python_version_2: 3.10.4
      branch: ${{ github.ref }}
  python-tensorflow:
    needs: changes
    if: ${{ needs.changes.outputs.python-tensorflow == 'true' }}
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: python-tensorflow
      context: python-tensorflow
      test: true
      base_image: python-minimal
      python_version_1: 3.9.13
      python_version_2: 3.10.4
      branch: ${{ github.ref }}
  r-minimal:
    needs: changes
    if: ${{ needs.changes.outputs.r-minimal == 'true' }}
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: r-minimal
      context: r-minimal
      test: true
      base_image: base
      r_version_1: 4.1.3
      r_version_2: 4.2.1
      branch: ${{ github.ref }}
  r-datascience:
    needs: changes
    if: ${{ needs.changes.outputs.r-datascience == 'true' }}
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: r-datascience
      context: r-datascience
      test: true
      base_image: r-minimal
      r_version_1: 4.1.3
      r_version_2: 4.2.1
      branch: ${{ github.ref }}
  jupyter-python:
    needs: changes
    if: ${{ needs.changes.outputs.jupyter == 'true' }}
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: jupyter-python
      context: jupyter
      test: true
      base_image: python-datascience
      python_version_1: 3.9.13
      python_version_2: 3.10.4
      branch: ${{ github.ref }}
  vscode-python:
    needs: changes
    if: ${{ needs.changes.outputs.vscode == 'true' }}
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: vscode-python
      context: vscode
      test: true
      base_image: python-datascience
      python_version_1: 3.9.13
      python_version_2: 3.10.4
      branch: ${{ github.ref }}
  pyspark:
    needs: changes
    if: ${{ needs.changes.outputs.spark == 'true' }}
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: pyspark
      context: spark
      test: true
      base_image: python-minimal
      python_version_1: 3.9.13
      python_version_2: 3.10.4
      spark_version: 3.3.0
      branch: ${{ github.ref }}
  jupyter-pyspark:
    needs: changes
    if: ${{ needs.changes.outputs.jupyter == 'true' }}
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: jupyter-pyspark
      context: jupyter
      test: true
      base_image: pyspark
      python_version_1: 3.9.13
      python_version_2: 3.10.4
      spark_version: 3.3.0
      branch: ${{ github.ref }}
  vscode-pyspark:
    needs: changes
    if: ${{ needs.changes.outputs.vscode == 'true' }}
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: vscode-pyspark
      context: vscode
      test: true
      base_image: pyspark
      python_version_1: 3.9.13
      python_version_2: 3.10.4
      spark_version: 3.3.0
      branch: ${{ github.ref }}
  jupyter-pytorch:
    needs: changes
    if: ${{ needs.changes.outputs.jupyter == 'true' }}
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: jupyter-pytorch
      context: jupyter
      test: true
      base_image: python-pytorch
      python_version_1: 3.9.13
      python_version_2: 3.10.4
      branch: ${{ github.ref }}
  vscode-pytorch:
    needs: changes
    if: ${{ needs.changes.outputs.vscode == 'true' }}
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: vscode-pytorch
      context: vscode
      test: true
      base_image: python-pytorch
      python_version_1: 3.9.13
      python_version_2: 3.10.4
      branch: ${{ github.ref }}
  jupyter-tensorflow:
    needs: changes
    if: ${{ needs.changes.outputs.jupyter == 'true' }}
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: jupyter-tensorflow
      context: jupyter
      test: true
      base_image: python-tensorflow
      python_version_1: 3.9.13
      python_version_2: 3.10.4
      branch: ${{ github.ref }}
  vscode-tensorflow:
    needs: changes
    if: ${{ needs.changes.outputs.vscode == 'true' }}
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: vscode-tensorflow
      context: vscode
      test: true
      base_image: python-tensorflow
      python_version_1: 3.9.13
      python_version_2: 3.10.4
      branch: ${{ github.ref }}
  rstudio:
    needs: changes
    if: ${{ needs.changes.outputs.rstudio == 'true' }}
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: rstudio
      context: rstudio
      test: true
      base_image: r-datascience
      r_version_1: 4.1.3
      r_version_2: 4.2.1
      branch: ${{ github.ref }}
  sparkr:
    needs: changes
    if: ${{ needs.changes.outputs.spark == 'true' }}
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: sparkr
      context: spark
      test: true
      base_image: r-minimal
      r_version_1: 4.1.3
      r_version_2: 4.2.1
      spark_version: 3.3.0
      branch: ${{ github.ref }}
  rstudio-sparkr:
    needs: changes
    if: ${{ needs.changes.outputs.rstudio == 'true' }}
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: rstudio-sparkr
      context: rstudio
      test: true
      base_image: sparkr
      r_version_1: 4.1.3
      r_version_2: 4.2.1
      spark_version: 3.3.0
      branch: ${{ github.ref }}
  jupyter-r:
    needs: changes
    if: ${{ needs.changes.outputs.jupyter == 'true' }}
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: jupyter-r
      context: jupyter
      test: true
      base_image: r-datascience
      r_version_1: 4.1.3
      r_version_2: 4.2.1
      branch: ${{ github.ref }}
  r-python-julia:
    needs: changes
    if: ${{ needs.changes.outputs.r-python-julia == 'true' }}
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: r-python-julia
      context: r-python-julia
      test: true
      base_image: r-minimal
      r_version_1: 4.2.1
      branch: ${{ github.ref }}
  vscode-r-python-julia:
    needs: changes
    if: ${{ needs.changes.outputs.vscode == 'true' }}
    uses: ./.github/workflows/main-workflow-template.yml
    with:
      image: vscode-r-python-julia
      context: vscode
      test: true
      base_image: r-python-julia
      r_version_1: 4.2.1
      branch: ${{ github.ref }}
