name: rstudio-sparkr

on:
  workflow_dispatch:
  workflow_run:
    workflows: [sparkr]
    types:
      - completed

jobs:
  base:
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    uses: .github/workflows/main-workflow-template.yml
    with:
      image: rstudio-sparkr
      context: rstudio
      test: false
      push: true
      base_image: inseefrlab/onyxia-sparkr:latest
      base_image_gpu: inseefrlab/onyxia-sparkr:latest-gpu
