name: scan all images

on:
  workflow_dispatch:
        
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        image: ['inseefrlab/onyxia-base:latest', 'inseefrlab/onyxia-base:latest-gpu',
                 'inseefrlab/onyxia-python:latest', 'inseefrlab/onyxia-python:latest-gpu',
                 'inseefrlab/onyxia-jupyter-python:latest', 'inseefrlab/onyxia-jupyter-python:latest-gpu',
                 'inseefrlab/onyxia-vscode-python:latest', 'inseefrlab/onyxia-vscode-python:latest-gpu',
                 'inseefrlab/onyxia-pyspark:latest', 'inseefrlab/onyxia-pyspark:latest-gpu',
                 'inseefrlab/onyxia-rstudio:latest', 'inseefrlab/onyxia-rstudio:latest-gpu',
                 'inseefrlab/onyxia-sparkr:latest', 'inseefrlab/onyxia-sparkr:latest-gpu',
                 'inseefrlab/onyxia-rstudio-sparkr:latest', 'inseefrlab/onyxia-rstudio-sparkr:latest-gpu']
    name: scan images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ matrix.image }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          timeout: '30m0s'
          security-checks: 'vuln'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
          category: ${{ matrix.image }}
