name: sparkr

on:
  workflow_dispatch:
  workflow_run:
    workflows: [r]
    types:
      - completed

jobs:
  base:
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    uses: .github/workflows/main-workflow-template.yml
    with:
      image: sparkr
      context: spark
      test: false
      push: true
      base_image: inseefrlab/onyxia-r:latest
      base_image_gpu: inseefrlab/onyxia-r:latest-gpu
