name: tag workflow

on:
  workflow_dispatch:

jobs:
  push:
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    uses: ./.github/workflows/tag-workflow-and-push-template.yml
    with:
      python_version_1: 3.9.13
      python_version_2: 3.10.4
      spark_version: 3.2.0
      r_version_1: 4.1.2
      r_version_2: 4.2.3
      # r_versions: >-
      #   [
      #     "4.2.3",
      #     "4.1.2"
      #   ]
      # python_versions: >-
      #   [
      #     "4.2.3",
      #     "4.1.2"
      #   ]
      # spark_versions: >-
      #   [
      #     "3.2.0",
      #     "3.3.0"
      #   ]