name: vscode-python

on:
  workflow_dispatch:
  workflow_run:
    workflows: [python]
    types:
      - completed

jobs:
  base:
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    uses: .github/workflows/main-workflow-template.yml
    with:
      image: vscode-python
      context: vscode
      test: false
      push: true
      base_image: inseefrlab/onyxia-python:latest
      base_image_gpu: inseefrlab/onyxia-python:latest-gpu
